spring.application.name=backend
server.port=${PORT:8080}
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d6hf771drdic73clghf0-a.virginia-postgres.render.com/pruebin?sslmode=require}
spring.datasource.username=${DB_USER:pruebin_user}
spring.datasource.password=${DB_PASSWORD:AMP8ffGJv4miiuPE1KFiOzGkFd4Bn0Ds}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true