spring.application.name=backend
server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d5qc65hr0fns73dfkk7g-a.virginia-postgres.render.com/back_eccomerce}
spring.datasource.username=${DB_USER:back_eccomerce_user}
spring.datasource.password=${DB_PASSWORD:PRjVxyXGVqbyJsiup7f0D1gxqrVvPGYr}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true