spring.application.name=backend
server.port=${PORT:8080}
<<<<<<< HEAD

spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d746jk15pdvs7382bog0-a.oregon-postgres.render.com/db_java_curso}
spring.datasource.username=${DB_USER:db_java_curso_user}
spring.datasource.password=${DB_PASSWORD:ZckSrDiod82IFpK7RqdwbkktlYMncKkX}
=======
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d6hf771drdic73clghf0-a.virginia-postgres.render.com/pruebin?sslmode=require}
spring.datasource.username=${DB_USER:pruebin_user}
spring.datasource.password=${DB_PASSWORD:AMP8ffGJv4miiuPE1KFiOzGkFd4Bn0Ds}
>>>>>>> 5aeef0a6615a195e887f0a9909c2a3c99341950c
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
